### ISSUE TITLE
Compiled binaries?

### ISSUE THREAD

**Issue by EnekoT2001** [discimagechef/dicremote#13]
It'd make it way more accessible if compiled binaries were provided. Even if just for Windows, that'd be all I need to dump a weird card (i need a sdhci card reader for that which i do have, but i also need 64bits to run regular aaru and is basically impossible to find both of these things in the same laptop, so this is all i can use to dump it and no idea how to compile it at all)

**Comment by claunia** [comment]
Hi,

Sorry but due to the differences in C library versions providing binaries would require a work that is not due while `aaruremote` is still in beta phase.

We plan to do in the future.

However you can ask for help in our Discord channel and a member of the team or maybe a collaborator may be able to provide you with an appropriate binary.

Also the recommended route for dumping SD cards is using Linux where compilation is quite easy (again help will be given in the Discord channel), and if you insist on using Windows, regular Aaru still run in 32-bit Windows [from the download here.](https://github.com/aaru-dps/Aaru/releases/download/v5.3.2/aaru-5.3.2_windows_x86.zip)

**Comment by EnekoT2001** [comment]
Thank you, i'll try the 32bit windows build but i think i checked it in the past and needed win 7+ and i cant use that os because the CPU on this laptop doesn't have PAE nor NX support, i think I misremembered that for not having 32bit support sorry.

I'll check the discord out too, i could try to compile myself if someone helps me with what i need to install tbh but as is i have no idea. Thank you for your reply
